# cargo-deny configuration for Orbit-RS
# https://embarkstudios.github.io/cargo-deny/

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "all"  # Changed back to "all" - using ignore list to handle specific advisories
yanked = "warn"
# Ignore unmaintained crates where no viable alternatives exist or migration is complex
ignore = [
    "RUSTSEC-2025-0012", # backoff - unmaintained, complex to replace in current usage
    "RUSTSEC-2024-0388", # derivative - unmaintained, widely used in generated code
    "RUSTSEC-2024-0384", # instant - unmaintained, used transitively
    "RUSTSEC-2024-0436", # paste - unmaintained, but still functional and widely used
    "RUSTSEC-2024-0370", # proc-macro-error - unmaintained, used transitively
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0", # Boost Software License 1.0 (needed for xxhash-rust dependency of fastbloom-rs)
    "CDLA-Permissive-2.0",
    "ISC",
    "OpenSSL",
    "Unicode-3.0",
    "Zlib",
    "BlueOak-1.0.0",
]
confidence-threshold = 0.8

# Allow specific crates that don't have license fields but are safe
[[licenses.exceptions]]
name = "jsonpath-rust"
allow = ["MIT"]

[[licenses.exceptions]]
name = "orbit-integration-tests"
allow = ["MIT"]

[[licenses.exceptions]]
name = "saga-example"
allow = ["MIT"]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# Skip checking for certain crates that have multiple versions in the dependency tree
skip = [
    { name = "bitflags" },
    { name = "syn" },
    { name = "windows-sys" },
    { name = "windows_x86_64_msvc" },
    { name = "axum" },
    { name = "axum-core" },
    { name = "base64" },
    { name = "core-foundation" },
    { name = "fixedbitset" },
    { name = "getrandom" },
    { name = "h2" },
    { name = "hashbrown" },
    { name = "heck" },
    { name = "http" },
    { name = "http-body" },
    { name = "hyper" },
    { name = "hyper-timeout" },
    { name = "indexmap" },
    { name = "itertools" },
    # Additional duplicates found
    { name = "linux-raw-sys" },
    { name = "multimap" },
    { name = "nom" },
    { name = "petgraph" },
    { name = "prettyplease" },
    { name = "prost" },
    { name = "prost-build" },
    { name = "prost-derive" },
    { name = "prost-types" },
    { name = "rand" },
    { name = "rand_chacha" },
    { name = "rand_core" },
    { name = "regex-syntax" },
    { name = "rustix" },
    { name = "rustls" },
    { name = "rustls-pemfile" },
    { name = "rustls-webpki" },
    { name = "security-framework" },
    { name = "socket2" },
    { name = "sync_wrapper" },
    { name = "thiserror" },
    { name = "thiserror-impl" },
    { name = "tokio-rustls" },
    { name = "tonic" },
    { name = "tonic-build" },
    { name = "tower" },
    { name = "tower-http" },
    { name = "wasi" },
    { name = "webpki-roots" },
    { name = "windows-link" },
    { name = "windows-result" },
    { name = "windows-strings" },
    { name = "windows-targets" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-git = [
    "https://github.com/ravituringworks/sqlx-no-rsa.git",
]
