[package]
name = "vector-store-example"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[[bin]]
name = "vector-store"
path = "src/main.rs"

[dependencies]
orbit-client = { path = "../../orbit-client" }
orbit-shared = { path = "../../orbit-shared" }
orbit-protocols = { path = "../../orbit-protocols" }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0"