-- ============================================================================
-- Healthcare ML Industry Example - Orbit-RS
-- ============================================================================
-- Use Case: Patient Risk Prediction, Medical Image Analysis, Drug Discovery
-- Protocols: PostgreSQL (SQL), Vector Search, Time Series
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. PATIENT RISK PREDICTION
-- ----------------------------------------------------------------------------

-- Create patient records table
CREATE TABLE IF NOT EXISTS patients (
    patient_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INTEGER,
    gender VARCHAR(10),
    blood_type VARCHAR(5),
    admission_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    diagnosis TEXT,
    vital_signs JSONB,
    risk_score FLOAT
);

-- Insert sample patient data
INSERT INTO patients (name, age, gender, blood_type, diagnosis, vital_signs) VALUES
('John Doe', 65, 'M', 'A+', 'Hypertension', '{"heart_rate": 85, "bp_systolic": 140, "bp_diastolic": 90, "temperature": 98.6}'),
('Jane Smith', 72, 'F', 'O-', 'Diabetes Type 2', '{"heart_rate": 78, "bp_systolic": 130, "bp_diastolic": 85, "temperature": 98.4, "glucose": 180}'),
('Bob Johnson', 58, 'M', 'B+', 'Coronary Artery Disease', '{"heart_rate": 92, "bp_systolic": 150, "bp_diastolic": 95, "temperature": 99.1}');

-- ML-based risk prediction using patient features
-- Note: In production, this would call an ML model via Orbit's ML subsystem
CREATE OR REPLACE FUNCTION predict_patient_risk(
    p_age INTEGER,
    p_heart_rate INTEGER,
    p_bp_systolic INTEGER,
    p_bp_diastolic INTEGER
) RETURNS FLOAT AS $$
DECLARE
    risk_score FLOAT;
BEGIN
    -- Simplified risk calculation (in production, use ML model)
    risk_score := (p_age * 0.3) + 
                  (p_heart_rate * 0.2) + 
                  (p_bp_systolic * 0.3) + 
                  (p_bp_diastolic * 0.2);
    RETURN risk_score / 100.0;
END;
$$ LANGUAGE plpgsql;

-- Update risk scores for all patients
UPDATE patients 
SET risk_score = predict_patient_risk(
    age,
    (vital_signs->>'heart_rate')::INTEGER,
    (vital_signs->>'bp_systolic')::INTEGER,
    (vital_signs->>'bp_diastolic')::INTEGER
);

-- Query high-risk patients
SELECT patient_id, name, age, diagnosis, risk_score
FROM patients
WHERE risk_score > 0.7
ORDER BY risk_score DESC;

-- ----------------------------------------------------------------------------
-- 2. MEDICAL IMAGE EMBEDDINGS & SIMILARITY SEARCH
-- ----------------------------------------------------------------------------

-- Create medical images table with vector embeddings
CREATE TABLE IF NOT EXISTS medical_images (
    image_id SERIAL PRIMARY KEY,
    patient_id INTEGER REFERENCES patients(patient_id),
    image_type VARCHAR(50), -- 'X-Ray', 'MRI', 'CT Scan'
    body_part VARCHAR(50),
    scan_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    diagnosis VARCHAR(200),
    image_embedding vector(512), -- 512-dimensional embedding from CNN
    metadata JSONB
);

-- Insert sample medical image embeddings
-- In production, these would be generated by a CNN model
INSERT INTO medical_images (patient_id, image_type, body_part, diagnosis, image_embedding, metadata) VALUES
(1, 'X-Ray', 'Chest', 'Normal', 
 array_fill(random()::float, ARRAY[512])::vector(512),
 '{"resolution": "1024x1024", "quality": "high"}'),
(2, 'MRI', 'Brain', 'No abnormalities', 
 array_fill(random()::float, ARRAY[512])::vector(512),
 '{"resolution": "512x512", "contrast": true}'),
(3, 'CT Scan', 'Heart', 'Calcification detected', 
 array_fill(random()::float, ARRAY[512])::vector(512),
 '{"slice_thickness": "1mm", "contrast": true}');

-- Create vector index for fast similarity search
CREATE INDEX IF NOT EXISTS medical_images_embedding_idx 
ON medical_images USING ivfflat (image_embedding vector_cosine_ops);

-- Find similar medical images using vector similarity
-- Useful for finding similar cases or anomaly detection
SELECT 
    m1.image_id,
    m1.image_type,
    m1.body_part,
    m1.diagnosis,
    1 - (m1.image_embedding <=> m2.image_embedding) AS similarity_score
FROM medical_images m1
CROSS JOIN medical_images m2
WHERE m1.image_id = 1 AND m2.image_id != 1
ORDER BY m1.image_embedding <=> m2.image_embedding
LIMIT 5;

-- ----------------------------------------------------------------------------
-- 3. PATIENT VITAL SIGNS TIME SERIES
-- ----------------------------------------------------------------------------

-- Create time series table for continuous monitoring
CREATE TABLE IF NOT EXISTS vital_signs_timeseries (
    ts_id SERIAL PRIMARY KEY,
    patient_id INTEGER REFERENCES patients(patient_id),
    timestamp BIGINT NOT NULL, -- Unix timestamp in milliseconds
    metric_name VARCHAR(50), -- 'heart_rate', 'blood_pressure', 'oxygen_saturation'
    value FLOAT NOT NULL,
    unit VARCHAR(20)
);

-- Insert time series data for patient monitoring
INSERT INTO vital_signs_timeseries (patient_id, timestamp, metric_name, value, unit) VALUES
(1, extract(epoch from now())::bigint * 1000, 'heart_rate', 85, 'bpm'),
(1, extract(epoch from now())::bigint * 1000 + 60000, 'heart_rate', 87, 'bpm'),
(1, extract(epoch from now())::bigint * 1000 + 120000, 'heart_rate', 84, 'bpm'),
(1, extract(epoch from now())::bigint * 1000, 'oxygen_saturation', 98, '%'),
(1, extract(epoch from now())::bigint * 1000 + 60000, 'oxygen_saturation', 97, '%');

-- Query vital signs with aggregation (moving average)
SELECT 
    patient_id,
    metric_name,
    AVG(value) OVER (
        PARTITION BY patient_id, metric_name 
        ORDER BY timestamp 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS moving_avg,
    value AS current_value,
    timestamp
FROM vital_signs_timeseries
WHERE patient_id = 1
ORDER BY timestamp DESC;

-- Detect anomalies in vital signs (values outside normal range)
SELECT 
    patient_id,
    metric_name,
    value,
    timestamp,
    CASE 
        WHEN metric_name = 'heart_rate' AND (value < 60 OR value > 100) THEN 'ALERT'
        WHEN metric_name = 'oxygen_saturation' AND value < 95 THEN 'CRITICAL'
        ELSE 'NORMAL'
    END AS alert_status
FROM vital_signs_timeseries
WHERE patient_id = 1
ORDER BY timestamp DESC;

-- ----------------------------------------------------------------------------
-- 4. DRUG INTERACTION PREDICTION
-- ----------------------------------------------------------------------------

-- Create medications table
CREATE TABLE IF NOT EXISTS medications (
    medication_id SERIAL PRIMARY KEY,
    drug_name VARCHAR(100) NOT NULL,
    drug_class VARCHAR(100),
    chemical_structure_embedding vector(256), -- Molecular fingerprint
    side_effects TEXT[],
    contraindications TEXT[]
);

-- Insert sample medications
INSERT INTO medications (drug_name, drug_class, chemical_structure_embedding, side_effects, contraindications) VALUES
('Aspirin', 'NSAID', array_fill(random()::float, ARRAY[256])::vector(256), 
 ARRAY['stomach upset', 'bleeding'], ARRAY['hemophilia', 'peptic ulcer']),
('Metformin', 'Antidiabetic', array_fill(random()::float, ARRAY[256])::vector(256),
 ARRAY['nausea', 'diarrhea'], ARRAY['kidney disease', 'liver disease']),
('Lisinopril', 'ACE Inhibitor', array_fill(random()::float, ARRAY[256])::vector(256),
 ARRAY['dizziness', 'dry cough'], ARRAY['pregnancy', 'angioedema']);

-- Create patient prescriptions table
CREATE TABLE IF NOT EXISTS prescriptions (
    prescription_id SERIAL PRIMARY KEY,
    patient_id INTEGER REFERENCES patients(patient_id),
    medication_id INTEGER REFERENCES medications(medication_id),
    dosage VARCHAR(50),
    frequency VARCHAR(50),
    start_date DATE,
    end_date DATE
);

-- Check for potential drug interactions using vector similarity
-- Similar chemical structures may indicate interaction risk
SELECT 
    m1.drug_name AS drug1,
    m2.drug_name AS drug2,
    1 - (m1.chemical_structure_embedding <=> m2.chemical_structure_embedding) AS similarity,
    CASE 
        WHEN 1 - (m1.chemical_structure_embedding <=> m2.chemical_structure_embedding) > 0.8 
        THEN 'HIGH INTERACTION RISK'
        WHEN 1 - (m1.chemical_structure_embedding <=> m2.chemical_structure_embedding) > 0.6 
        THEN 'MODERATE RISK'
        ELSE 'LOW RISK'
    END AS risk_level
FROM medications m1
CROSS JOIN medications m2
WHERE m1.medication_id < m2.medication_id
ORDER BY similarity DESC;

-- ----------------------------------------------------------------------------
-- 5. CLINICAL TRIAL PATIENT MATCHING
-- ----------------------------------------------------------------------------

-- Create clinical trials table
CREATE TABLE IF NOT EXISTS clinical_trials (
    trial_id SERIAL PRIMARY KEY,
    trial_name VARCHAR(200),
    condition VARCHAR(100),
    inclusion_criteria JSONB,
    exclusion_criteria JSONB,
    phase VARCHAR(20),
    status VARCHAR(50)
);

-- Insert sample clinical trial
INSERT INTO clinical_trials (trial_name, condition, inclusion_criteria, exclusion_criteria, phase, status) VALUES
('Hypertension Drug Trial', 'Hypertension', 
 '{"age_min": 40, "age_max": 75, "bp_systolic_min": 140}',
 '{"pregnant": true, "kidney_disease": true}',
 'Phase III', 'Recruiting');

-- Match patients to clinical trials using ML-based criteria
SELECT 
    p.patient_id,
    p.name,
    p.age,
    p.diagnosis,
    ct.trial_name,
    ct.phase,
    CASE 
        WHEN p.age >= (ct.inclusion_criteria->>'age_min')::INTEGER 
         AND p.age <= (ct.inclusion_criteria->>'age_max')::INTEGER
         AND (p.vital_signs->>'bp_systolic')::INTEGER >= (ct.inclusion_criteria->>'bp_systolic_min')::INTEGER
        THEN 'ELIGIBLE'
        ELSE 'NOT ELIGIBLE'
    END AS eligibility_status
FROM patients p
CROSS JOIN clinical_trials ct
WHERE ct.status = 'Recruiting'
  AND p.diagnosis ILIKE '%' || ct.condition || '%';

-- ----------------------------------------------------------------------------
-- 6. PREDICTIVE ANALYTICS - READMISSION RISK
-- ----------------------------------------------------------------------------

-- Create hospital admissions table
CREATE TABLE IF NOT EXISTS hospital_admissions (
    admission_id SERIAL PRIMARY KEY,
    patient_id INTEGER REFERENCES patients(patient_id),
    admission_date TIMESTAMP,
    discharge_date TIMESTAMP,
    length_of_stay INTEGER,
    diagnosis VARCHAR(200),
    procedures TEXT[],
    readmission_30day BOOLEAN DEFAULT FALSE
);

-- ML model to predict 30-day readmission risk
CREATE OR REPLACE FUNCTION predict_readmission_risk(
    p_age INTEGER,
    p_length_of_stay INTEGER,
    p_num_procedures INTEGER,
    p_risk_score FLOAT
) RETURNS FLOAT AS $$
DECLARE
    readmission_probability FLOAT;
BEGIN
    -- Simplified logistic regression (in production, use trained ML model)
    readmission_probability := 1.0 / (1.0 + exp(-(
        -2.5 + 
        (p_age * 0.02) + 
        (p_length_of_stay * 0.15) + 
        (p_num_procedures * 0.3) +
        (p_risk_score * 2.0)
    )));
    RETURN readmission_probability;
END;
$$ LANGUAGE plpgsql;

-- Identify high-risk patients for readmission
SELECT 
    p.patient_id,
    p.name,
    p.age,
    ha.length_of_stay,
    array_length(ha.procedures, 1) AS num_procedures,
    p.risk_score,
    predict_readmission_risk(
        p.age, 
        ha.length_of_stay, 
        COALESCE(array_length(ha.procedures, 1), 0),
        p.risk_score
    ) AS readmission_probability
FROM patients p
JOIN hospital_admissions ha ON p.patient_id = ha.patient_id
WHERE ha.discharge_date IS NOT NULL
ORDER BY readmission_probability DESC;

-- ============================================================================
-- SUMMARY: Healthcare ML Use Cases Demonstrated
-- ============================================================================
-- 1. Patient risk stratification using ML models
-- 2. Medical image similarity search with vector embeddings
-- 3. Real-time vital signs monitoring with time series
-- 4. Drug interaction prediction using molecular embeddings
-- 5. Clinical trial patient matching with ML criteria
-- 6. Predictive analytics for hospital readmission risk
-- ============================================================================
