apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orbit-rs.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orbit-rs.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  orbit-server.toml: |
    {{- include "orbit-rs.config" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orbit-rs.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orbit-rs.labels" . | nindent 4 }}
    app.kubernetes.io/component: scripts
data:
  entrypoint.sh: |
    {{- include "orbit-rs.entrypoint" . | nindent 4 }}
  healthcheck.sh: |
    {{- include "orbit-rs.healthcheck" . | nindent 4 }}