# Jekyll Configuration for Orbit-RS Documentation
# Configured for GitHub Flavored Markdown (GFM) compatibility
# Last updated: October 2025

title: Orbit-RS Documentation
description: The Next-Generation Distributed Database System - Production-Ready Multi-Model Platform
url: https://turingworks.github.io
baseurl: /orbit-rs

# GitHub Pages and Jekyll configuration
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links

# Navigation structure
header_pages:
  - index.md
  - PROJECT_OVERVIEW.md
  - QUICK_START.md
  - ROADMAP_CONSOLIDATED.md
  - BACKLOG_CONSOLIDATED.md
  - CONTRIBUTING.md

# Site configuration
markdown: kramdown
highlighter: rouge

# GitHub Flavored Markdown configuration
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# SEO and social
author: TuringWorks
twitter:
  username: TuringWorksAI
facebook:
  username: TuringWorksAI
social:
  name: TuringWorks
  links:
    - https://github.com/TuringWorks/orbit-rs
    - https://discord.gg/orbit-rs
    - https://twitter.com/TuringWorksAI

# Collections for organized content
collections:
  phases:
    output: true
    permalink: /:collection/:name/
  features:
    output: true
    permalink: /:collection/:name/
  operations:
    output: true
    permalink: /:collection/:name/
  deployment:
    output: true
    permalink: /:collection/:name/
  tutorials:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "TuringWorks Team"
  - scope:
      path: ""
      type: "phases"
    values:
      layout: "default"
      category: "development"
  - scope:
      path: ""
      type: "features"
    values:
      layout: "default"
      category: "features"
  - scope:
      path: ""
      type: "operations"
    values:
      layout: "default"
      category: "operations"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - target/
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Include additional files
include:
  - _pages
  - assets/css/custom.css

# Custom CSS for styling
custom_css:
  - "/orbit-rs/assets/css/custom.css"

# Additional Jekyll settings
# Enable GitHub Flavored Markdown features
gfm_quirks: paragraph_end

# Additional GFM support
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Repository information for GitHub integration
repository: TuringWorks/orbit-rs
github: [metadata]
